name: reminder_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^14.0.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/target.png
    - assets/icons/Add Task.png
    - assets/icons/search.png
    - assets/icons/View Tasks.png
    - assets/images/reminder.png
    - assets/icons/pencil.svg
    - assets/icons/trash-xmark.svg


url_launcher :
  android_package_name : com.example.myapp
  ios_bundle_id : com.example.myapp
  handles :
   -tel
